# permissions to do viewer performancemonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: performancemonitor-viewer-role
rules:
- apiGroups:
  - pervcheck.k8s.accountr.eu
  resources:
  - performancemonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pervcheck.k8s.accountr.eu
  resources:
  - performancemonitors/status
  verbs:
  - get
